In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import sys
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("/home/yash/ML/Customer_Churn_Prediction/data/customer_churn_prediction_dataset.csv")
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST00001,Female,0,Yes,No,31,Yes,No,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer,73.50,2189.97,Yes
1,CUST00002,Female,0,No,Yes,26,Yes,Yes,DSL,No,...,No,Yes,No,No,Month-to-month,Yes,Electronic check,112.53,2974.83,Yes
2,CUST00003,Female,0,Yes,No,7,No,No,DSL,No,...,Yes,No,No,Yes,Two year,Yes,Electronic check,94.03,648.59,Yes
3,CUST00004,Male,1,Yes,No,17,Yes,No,No,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,55.39,840.61,No
4,CUST00005,Male,0,Yes,Yes,38,No,Yes,DSL,No,...,No,No,Yes,Yes,Month-to-month,Yes,Credit card,85.85,3182.86,No

In [3]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=["Churn"]), df["Churn"], test_size=0.2,random_state=0)

In [4]:
sys.path.append("/home/yash/ML/Customer_Churn_Prediction")

from preprocessing.Preprocessing import Preprocessing_data

preprocessing = Preprocessing_data(x_train, x_test)

In [5]:
preprocessing.missing_values()

In [6]:
preprocessing.Scaling()

In [7]:
preprocessing.Encoding()

In [8]:
x_train, x_test = preprocessing.Get_Processed_Data()

In [9]:
x_train

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
2370,0,0.323944,0.500467,0.190490,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1774,1,0.788732,0.375421,0.337088,1.0,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
731,0,0.661972,0.468505,0.360021,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
271,1,0.901408,0.585794,0.653803,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1077,0,0.619718,0.458879,0.372000,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,0,0.154930,0.603084,0.097693,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0
835,0,0.478873,0.420280,0.242012,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1653,0,0.873239,0.426075,0.479037,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2607,0,0.338028,0.660841,0.245972,0.0,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2732,0,0.352113,0.494673,0.198270,0.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [10]:
x_test

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
311,0,0.225352,0.752150,0.172973,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1025,1,0.028169,0.499065,0.019550,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1587,0,1.000000,0.440748,0.533576,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2941,0,0.802817,0.425981,0.408714,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2980,1,0.422535,0.398692,0.184217,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0,0.676056,0.193084,0.216524,0.0,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1431,0,0.338028,0.354860,0.160511,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
654,0,0.774648,0.378972,0.374796,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
476,0,0.464789,0.486449,0.266940,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
2326,0,0.309859,0.835140,0.302148,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0

In [11]:
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [12]:
y_pred = lr.predict(x_test)

In [13]:
print(accuracy_score(y_test,y_pred))

0.78

In [ ]:
print(y_pred)